### PR TITLE
Add technic to optional depends

### PR DESCRIPTION
**Pull request by hlqkj**
The technic exclusions in [init.lua#L25](https://github.com/minetest-mods/anvil/blob/master/init.lua#L25) were not working on my game because they were being executed before technic was loaded.

In general, when a mod references another this one should be listed in optional_depends to ensure a correct load order, so I added that (and also on depends.txt since it's still there).

Also, the two checks on [init.lua#L285](https://github.com/minetest-mods/anvil/blob/master/init.lua#L285) and 286 are actually useless. I this removed them since there is a dedicated API to do that: `anvil.make_unrepairable()`. Would be both redundant and bad separation of concerns...

I also suggest to add exclusions for all the other rechargeable technic tools, given that the mod already had some "support" technic items and considering that those tools make a tricky use of the itemstack wear. I can do aspecific PR if appreciated, would've been out of the scope of this one.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Thank you for your submission. The mod loading order is indeed not defined, hence this makes totally sense.

> I can do aspecific PR if appreciated, would've been out of the scope of this one.

Would you please be so nice and integrate it into this PR? I would prefer to not create a bug/issue by intent and fix it in a later PR. Two separate commits which are then pushed to master would be fine to me.

**Review by SmallJoker — APPROVED** [review]
Thanks. Looks good. Will merge in a few days.

**Comment by hlqkj** [comment]
Done. Thank you for approving this.

**Review by Panquesito7 — APPROVED** [review]

**Comment by hlqkj** [comment]
Sorry all, I did forget to add the different modes of the drills, just fixed that. Hope I didn't forget anything this time :)

**Pull request merged**
