### PR TITLE
Make item displacement variable global

### PR DESCRIPTION
**Pull request by tacotexmex**
So that it's configureable by other mods. Adding "anvil_" to make it unique.

### CODE REVIEW

**Comment by FaceDeer** [comment]
I'm not sure what this would be used for. The item displacement value was picked to make the item appear to rest on the upper surface of the anvil nodebox model, I suppose you'd want to change that if you modified the anvil's nodebox but if you're doing that then wouldn't you be able to change the value at the same time?

I'll probably go ahead and merge this, I don't see a reason not to, I'm just a bit puzzled. :)

**Comment by tacotexmex** [comment]
Hehe, I should've been less cryptic as of why. Your are correct by guessing it's for changing the nodebox. However, I'm doing this by using overrides from another mod in order to be able to get updates from the original repo, so if I could set that displacement value from outside, I'm good. 😊

**Comment by tacotexmex** [comment]
No merge?

Since it's still open I wanna state that I've seen other mods do global variables in this style:
```
anvil = {
  setting = {
    item_displacement = 10,
  }
}
```

Should I change?

**Comment by FaceDeer** [comment]
Oh, sorry, I got a bit distracted with real life over the past week or two.

Yeah, I was going to suggest using global variables of that style instead. The anvil mod also uses a global "tmp" variable (though only as an ephemeral hack to allow information to be passed between function calls that normally wouldn't pass information) and I was going to move that into an "anvil" global table member as well.

Thanks for the kick in the pants, I need to get back to this. If you change your PR that would simplify things a bit, so by all means please do. :)

**Pull request merged**
